spring:
  application:
    name: epilote-backend

server:
  port: 8080

couchbase:
  connection-string: ${CB_CONNECTION_STRING}
  username: ${CB_USERNAME}
  password: ${CB_PASSWORD}
  bucket: ${CB_BUCKET:epilote_prod}

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 3600000        # 1 heure
  refresh-expiration-ms: 2592000000  # 30 jours
  offline-expiration-ms: 2592000000  # 30 jours offline token

epilote:
  super-admin:
    email: ${SUPER_ADMIN_EMAIL:super@admin.cg}
    password: ${SUPER_ADMIN_PASSWORD:}

app-services:
  admin-url: ${APP_SERVICES_ADMIN_URL:https://x0by7zekx39pidsy.apps.cloud.couchbase.com:4985}
  admin-user: ${APP_SERVICES_ADMIN_USER:epilote-admin}
  admin-password: ${APP_SERVICES_ADMIN_PASSWORD:}

logging:
  level:
    root: WARN
    cg.epilote: INFO
    com.couchbase: WARN
