spring:
  application:
    name: epilote-backend

server:
  port: 8080

couchbase:
  connection-string: ${CB_CONNECTION_STRING:couchbases://cb.qfnlqsnztvyhsxs.cloud.couchbase.com}
  username: ${CB_USERNAME:PILOTE}
  password: ${CB_PASSWORD:}
  bucket: ${CB_BUCKET:epilote_prod}

jwt:
  secret: ${JWT_SECRET:epilote-secret-key-change-in-production-min-256-bits}
  expiration-ms: 3600000        # 1 heure
  refresh-expiration-ms: 2592000000  # 30 jours
  offline-expiration-ms: 2592000000  # 30 jours offline token

app-services:
  admin-url: ${APP_SERVICES_ADMIN_URL:https://x0by7zekx39pidsy.apps.cloud.couchbase.com:4985}
  admin-user: ${APP_SERVICES_ADMIN_USER:epilote-admin}
  admin-password: ${APP_SERVICES_ADMIN_PASSWORD:}

logging:
  level:
    cg.epilote: DEBUG
    com.couchbase: WARN
